### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by mcollina** [Level/rocksdb#1]
I need to setup prebuilts for all the envs, how do you folks do that?
Also, can you add me to the appveyor team (or how does that work)?

cc @ralphtheninja @juliangruber

**Comment by ralphtheninja** [comment]
@mcollina @juliangruber is probably the best person to ask but I can try and answer.

First you need `prebuild` and `prebuild-ci` as devDependencies and you need to add it to your test script, see leveldown

https://github.com/Level/leveldown/blob/master/package.json#L59

Also need to add a `PREBUILD_TOKEN` environment variable, see https://github.com/prebuild/prebuild-ci#usage for more information

Lets start with travis and setup appveyor after that

**Comment by vweevers** [comment]
> Also, can you add me to the appveyor team?

Done. That reminds me, we still have to create an email address for the org account.

> Also, is really https://github.com/Level/leveldown/blob/master/appveyor.yml#L22-L23 needed now with prebuild-ci?

It's an optimization to shorten build time (but the two lines could be combined into `for /f %%i in ('node -v') do prebuild -b %%i`). When the CI job arrives at the `prebuild-ci` step, the current node version has already been built so it can skip that. In Travis, we're building twice (but it's still faster than AppVeyor).

We can remove this for simplicity's sake, in both leveldown and rocksdb. I reckon it's the test suite that takes up the most time anyway.

**Comment by vweevers** [comment]
Opened Level/leveldb.org/issues/31 for the email address.

**Comment by mcollina** [comment]
I think this is almost ready to go. Do I need to configure some secrets for storing the prebuilt somewhere? Do I need to create a token?

**Comment by vweevers** [comment]
@mcollina I added the token in Appveyor for you

**Comment by mcollina** [comment]
May I have the publish rights to rocksdb?

**Comment by ralphtheninja** [comment]
@mcollina 

```
$ npm owner add matteo.collina rocksdb
+ matteo.collina (rocksdb)
$ npm owner ls rocksdb
matteo.collina <hello@matteocollina.com>
juliangruber <julian@juliangruber.com>
ralphtheninja <ralphtheninja@riseup.net>
rvagg <rod@vagg.org>
```

**Comment by mcollina** [comment]
As for security reasons, I cannot put my personal access token into travis. Do we have set up a user just for this purpose, so that it has access just for this? Or are we using some other form of authentication?

**Comment by mcollina** [comment]
Or can someone else in the org add theirs, or copy the one from leveldown to rocksdb.

cc @mafintosh you set that up, right?

**Comment by vweevers** [comment]
The @level-appveyor machine user exists for the same reason. We could use that for travis too, and perhaps rename it? LMK

**Comment by mcollina** [comment]
Definitely. Can you add the access token for that user to Travis?

**Comment by vweevers** [comment]
done

**Comment by vweevers** [comment]
Renamed to @level-ci.

**Comment by mcollina** [comment]
Pushed, let's see if it works.

**Comment by vweevers** [comment]
I like the look of this :)

![image](https://user-images.githubusercontent.com/3055345/27730933-6040b082-5d8b-11e7-821a-ea6efcabf848.png)

**Comment by mcollina** [comment]
@vweevers this is fantastic.

**Comment by ralphtheninja** [comment]
@mcollina Closing this.
