### ISSUE TITLE
add link to rocksdb in the readme

### ISSUE THREAD

**Issue by ralphtheninja** [Level/rocksdb#11]

**Comment by ralphtheninja** [comment]
@mcollina Do you know which version of rocksdb we are currently using? I'm guessing it's pretty outdated compared to latest https://github.com/facebook/rocksdb

**Comment by cjihrig** [comment]
It looks like 5.3.0 - https://github.com/Level/rocksdb/blob/05704936d1b5f0ea5f7647190ce1cfd791d37a5a/deps/leveldb/leveldb-rocksdb/include/rocksdb/version.h#L7-L9

**Comment by ralphtheninja** [comment]
e4ea9ea
