### ISSUE TITLE
Segmentation fault on Node.js 12.7.0

### ISSUE THREAD

**Issue by nazar-pc** [Level/rocksdb#129]
Doing anything with rocksdb on Node.js 12.7.0 results in following error:
```
Segmentation fault (core dumped)
```
On Linux this is what i see in kernel logs:
```
[ 8962.635016] node[32694]: segfault at 0 ip 00007fba46bc430b sp 00007fba46aa0e20 error 4 in node.napi.glibc.node[7fba46aa2000+348000]
[ 8962.635020] Code: 8b 57 50 48 8b 70 08 48 8b 47 48 48 89 55 c8 48 8b 57 60 48 89 45 c0 48 8b 47 58 48 89 55 d8 48 8d 57 40 4c 89 e7 48 89 45 d0 <48> 8b 06 ff 50 30 48 8d 43 28 49 39 c4 74 30 8b 45 b0 48 8b 7b 30
```

Tried to rebuild, but doesn't help, still the same error. Looks like modifications are needed to the library itself.

I'm on Ubuntu 19.10 if that makes any difference (yes, 19.10, rolling release).

**Comment by nazar-pc** [comment]
Same under `node:12.7.0` official Docker image, so this is not my machine that is broken

**Comment by vweevers** [comment]
Which version are you using? You need `rocksdb@4` for node 12. 

Can you define "Doing anything", preferably with a code example?

**Comment by nazar-pc** [comment]
Yes, I'm using latest available version, 4.

Reduced example:
```javascript
const RocksDB     = require("rocksdb");
const {promisify} = require("util");

(async () => {
    const rocksDb = new RocksDB('/tmp/test');
    await promisify(rocksDb.open.bind(rocksDb));
    rocksDb.put('1', '', () => {
        rocksDb.close(() => {
        });
    });
})();
```

Segfault happens on `rocksDb.put()`, but actual reason is `promisify(rocksDb.open.bind(rocksDb))`, no idea why though, seems to be correct.

**Comment by vweevers** [comment]
I suggest using the safer and more convenient [`level-rocksdb`](https://github.com/Level/level-rocksdb) with builtin promise support and no need to explicitly call `open()`:

```js
const level = require("level-rocksdb")

(async () => {
    const db = level('/tmp/test')
    await db.put('1', '')
})()
```

**Comment by nazar-pc** [comment]
I've already switched to that, but still this seems to be something that is worth fixing.

**Comment by vweevers** [comment]
> still this seems to be something that is worth fixing.

It's not a bug. I think that

```js
await promisify(rocksDb.open.bind(rocksDb))
```

Should have been:

```js
await promisify(rocksDb.open.bind(rocksDb))()
```

**Comment by nazar-pc** [comment]
Hm... you're right, thanks!
