### ISSUE TITLE
Pass options to rocksdb?

### ISSUE THREAD

**Issue by MeirionHughes** [Level/rocksdb#13]
Just testing this library and I noticed there are several Log.old.15036... files being generated.
 
[this ](https://github.com/facebook/rocksdb/issues/849) post says you can pass options to the c++ library, but don't know how you'd go about doing that with this library (no docs)

Is it possible to configure the number of old log files kept and/or disable logging entirely?

**Comment by mcollina** [comment]
I do not know, would you like to send a PR?

**Comment by ralphtheninja** [comment]
@MeirionHughes Passing options to the c++ side is not a problem. We just need to figure out what options to pass and document them.

**Comment by MeirionHughes** [comment]
okay, I'll take a peek if I get the chance and no one else has done it. those log files seem to get fat quickly. :D

**Comment by pibi** [comment]
Hi all. I was just looking for a way to pass options to rocksdb too. In my case I need to support openReadOnly for analysis purpose. I found that [rocksdb-node](https://github.com/dberesford/rocksdb-node#open-readonly) support that. Do you think it would be easier to wrap rocksdb-node?

**Comment by emschwartz** [comment]
I'm also interested in using the read-only option. Any word on what's the best way to do that? I'd like to keep using this version of rocksdb, if possible, because I really like the compatibility with the levelup/leveldown ecosystem.

**Comment by mingoes** [comment]
+1 for openReadyOnly support! Will try to use rocksdb-node for now.

**Comment by oiime** [comment]
+1 for openReadyOnly

**Comment by ralphtheninja** [comment]
Adding it to our project for now so we can at least prioritize it.

**Comment by ralphtheninja** [comment]
> Is it possible to configure the number of old log files kept and/or disable logging entirely?

@MeirionHughes We should look into how we can disable logging completely. We noticed that it messes up tests (after fixing the destroy-test, we noticed that folders were not deleted on windows). See linked issue.

**Comment by MeirionHughes** [comment]
I've forgotten everything about trying this - or even why. 😆 ... but didn't you need to have "some" log files for restoring state if it corrupts?

**Comment by bkniffler** [comment]
Is it possible to add options somehow? readOnly mode would be very cool!

**Comment by ralphtheninja** [comment]
@bkniffler It's definitely possible, we just haven't bothered with it yet. Currently focusing on tests and documentations for level as a whole, but we'll get to this as well.

**Comment by eugeneware** [comment]
For those interested if you change the `OpenDatabase` function in `database.cc` to this it will open it up in ReadOnly:

``` c++
rocksdb::Status Database::OpenDatabase (
        rocksdb::Options* options
    ) {
  return rocksdb::DB::OpenForReadOnly(*options, **location, &db);
}
```

So we just need to add some node options that call this instead of `rocksdb::DB::Open`.

**Comment by eugeneware** [comment]
I've created a PR for this in #98 and also published a personal fork of the leveldown module at [@eugeneware/rocksdb](https://www.npmjs.com/@eugeneware/rocksdb)

**Comment by vweevers** [comment]
Splitting this up:

- Support `readOnly`: done
- Disable info logs: #113

If there's another option you'd like to see supported, please open a new issue. Thanks!
