### ISSUE TITLE
Assertion `merge_operator_ != nullptr' failed.

### ISSUE THREAD

**Issue by dinikolop** [Level/rocksdb#152]
I have a small C++ program for writing into a RocksDB directory. In it, I have defined a Merge operator which I need for my use case. 
I want to use the `level/rocksdb` binding for reading this db, however when I try to get a value after successfully opening the db, I receive this error:
```
node: ../deps/leveldb/leveldb-rocksdb/table/get_context.cc:119: bool rocksdb::GetContext::SaveValue(const rocksdb::ParsedInternalKey&, const rocksdb::Slice&, rocksdb::Cleanable*): Assertion `merge_operator_ != nullptr' failed.
Aborted (core dumped)
```
I do not know the reason why this happens, but I suspect it might be related to the fact that merge operations have been performed and I need to define the same merge operator before opening the db for reading. If that is the case, is the merge feature supported? Any help much appreciated! Thanks :)

**Comment by vweevers** [comment]
> If that is the case, is the merge feature supported?

No, it isn't.

Maybe you could open the db with your C++ program, and somehow trick RocksDB into removing whatever metadata it wrote to the db for your merge operator? Taking a wild guess.. maybe doing a compaction will do the trick.

**Comment by dinikolop** [comment]
@vweevers, thank you for the advice. I will try to do so.

**Comment by dinikolop** [comment]
@vweevers compaction before reading does the trick, thanks! Changing any possible metadata for merge operator would be more efficient and I'll investigate a bit further. Closing this.
