### ISSUE TITLE
Which version of rocksdb and how/where is it documented?

### ISSUE THREAD

**Issue by ronag** [Level/rocksdb#159]
What version of rocksdb is included in 4.1.0? Does the npm version follow the rocksdb version, e.g. is it rocksdb 4.x?

**Comment by vweevers** [comment]
The npm package is independently versioned. Current RocksDB version is https://github.com/facebook/rocksdb/tree/4e0065015d3dab1d94ef7cb2b4b1d1fecfa0e926

We have a task in the backlog to make RocksDB a git submodule (https://github.com/Level/rocksdb/pull/141).
