### ISSUE TITLE
Destroy() creates directory on Windows

### ISSUE THREAD

**Issue by vweevers** [Level/rocksdb#30]
Repro:

```js
test('destroy does not create a directory', function (t) {
  t.plan(3)

  const location = path.resolve('destroy-test')

  rimraf.sync(location)
  t.is(fs.existsSync(location), false, 'exists before')

  leveldown.destroy(location, function (err) {
    t.ifError(err, 'no error')
    t.is(fs.existsSync(location), false, 'exists after') // Fails
  })
})
```

Here's the relevant C++, comments mine:

```c++
Status DestroyDB(const std::string& dbname /*, .. */) {
  FileLock* lock;
  const std::string lockname = LockFileName(dbname); // "<location>/LOCK"
  Status result = env->LockFile(lockname, &lock); // Creates <location>/LOCK
  
  if (result.ok()) {
    // Delete files..
    // ..

    env->UnlockFile(lock);
    env->DeleteFile(lockname); // Succeeds, directory is empty
    env->DeleteDir(dbname);    // Yet this fails
  }

  return result;
}
```

The `DeleteDir` fails (silently) with:

```
IO error: Failed to remove dir: D:\xx\Level\rocksdb\destroy-test: Directory not empty
```

**Comment by ralphtheninja** [comment]
@vweevers Great find!

**Comment by ralphtheninja** [comment]
I just had a quick look and this is in the upstream code.

**Comment by ralphtheninja** [comment]
Current master looks identical

https://github.com/facebook/rocksdb/blob/edc258127ef5e64469798e0fa3696e1a9131effd/db/db_impl.cc#L2434-L2439

**Comment by vweevers** [comment]
Open questions:

- Is all of this the same upstream?
- Can we disable the logger?

**Comment by ralphtheninja** [comment]
> Is all of this the same upstream?

Afaik, everything under `rocksdb/deps/leveldb/leveldb-rocksdb` is the same upstream.

> When is the logger closed?

No idea.

> Can we disable the logger?

Maybe we could through options (guessing here). There's https://github.com/Level/rocksdb/issues/13 that @MeirionHughes created. Might be related.

**Comment by ralphtheninja** [comment]
@vweevers What does the `LOG` file contain? Is it just for debugging?

**Comment by vweevers** [comment]
Yeah, info, warnings and errors it seems.

**Comment by ralphtheninja** [comment]
Sheesh. That's a tonne of i/o enabled by default.

**Comment by vweevers** [comment]
Oh no, I didn't check which log levels are enabled by default.

**Comment by vweevers** [comment]
Also I can't find an option to completely disable the log, but there is an option to change its path:

https://github.com/Level/rocksdb/blob/fc844ebaea89ce0b8a28e85d3ae386e30700295d/deps/leveldb/leveldb-rocksdb/db/auto_roll_logger.cc#L147-L148

**Comment by ralphtheninja** [comment]
Gawd. Logging should never be enabled by default :roll_eyes:

**Comment by ralphtheninja** [comment]
Hmm, but what about the caller of `CreateLoggerFromOptions()`

**Comment by ralphtheninja** [comment]
Was about to post an issue about it but if you have questions you need to use facebook lol.

**Comment by vweevers** [comment]
We *could* implement our own noop-logger and pass it to rocksdb via the options.

**Comment by vweevers** [comment]
See also https://github.com/facebook/rocksdb/issues/494.

**Comment by ralphtheninja** [comment]
I can't believe there's no option for turning off the logging completely. It seems you can only tune the log _level_ which is not what we want.

**Comment by ralphtheninja** [comment]
> We could implement our own noop-logger and pass it to rocksdb via the options.

We could also have a fork of the whole project, with logging disabled :grinning:

**Comment by vweevers** [comment]
Agree. Disabling logging not only fixes the destroy issue, but also, well, gets rid of the logging 😸 

It should be an option though (defaulting to disabled). And since this diverges from leveldown, we should also copy leveldown's API docs to here, and document the additional option(s).

How would it look like in JS-land?

```js
levelup(rocksdb(location), { log: true })
```

Or make it a loglevel, adding `none` to rocksdb's loglevels?

```js
levelup(rocksdb(location), { loglevel: 'none' }) // our default
levelup(rocksdb(location), { loglevel: 'info' })
levelup(rocksdb(location), { loglevel: 'warning' }) // etc 
```

Assuming there is such an option. I couldn't figure out if it's a build-time or runtime option.

**Comment by MeirionHughes** [comment]
[the docs kind of imply it isn't just a "log" file though](https://github.com/facebook/rocksdb/wiki/rocksdb-basics#3-high-level-architecture); it serves as a "backup" of the in-memory recent-commits before they are added to the main storage file. If there is a crash before the data is written, then the log file will be used to "reconstruct" the missing data. Remove that and you potentially lose data when/if you crash.

**Comment by vweevers** [comment]
@MeirionHughes I think (but could use confirmation) these are two different things. Here are the rocksdb file types:

https://github.com/Level/rocksdb/blob/fc844ebaea89ce0b8a28e85d3ae386e30700295d/deps/leveldb/leveldb-rocksdb/db/filename.h#L31-L42

I think you're talking about `kLogFile`, we're talking about `kInfoLogFile` ([this](https://github.com/facebook/rocksdb/wiki/Logger)).

**Comment by MeirionHughes** [comment]
ah ok; just double-checking. :P

**Comment by ralphtheninja** [comment]
@vweevers Some research

It seems that `ImmutableDBOptions` is taking care of cleaning up the `Logger` object:

https://github.com/Level/rocksdb/blob/fc844ebaea89ce0b8a28e85d3ae386e30700295d/deps/leveldb/leveldb-rocksdb/db/db_impl.cc#L6205-L6208

It has a member `std::shared_ptr<Logger> info_log;` which will be deleted, causing the `Logger`-destructor to be invoked when the `ImmutbleDBOptions` object exits out of scope, i.e. when `DestroyDB()` exits.

So this answers when the logger object dies. It in turn does `fclose(file_)` in all implementations, be it `PosixLogger` or `WinLogger`.

**Comment by vweevers** [comment]
That means that a simple `fs.rmdir(location)` in JS-land would also work.

**Comment by ralphtheninja** [comment]
So the problem we have is that `DestroyDB()` creates `LOG`, cleans up all files (but cleaning up `LOG` fails since it has an open handle), then the file handle is closed after.

I think `DestroyDB()` should not log at all, so in this case we should use a noop-logger unconditionally.

**Comment by ralphtheninja** [comment]
> That means that a simple fs.rmdir(location) in JS-land would also work.

That's probably the best fix!

**Comment by vweevers** [comment]
I'll try that out in a bit :)

**Comment by ralphtheninja** [comment]
I also made some logging in c++ land just to see when the `Logger` object was created/destroyed. Turns out that `db.close()` also closes the file, but once we do `db.repair()` the file is created again and then closed.

Just FYI.

**Comment by vweevers** [comment]
OK doing `fs.rmdir` works!

And I wanted to write a unit test, but we also have this:

https://github.com/Level/rocksdb/blob/fc844ebaea89ce0b8a28e85d3ae386e30700295d/test/destroy-test.js#L27-L33

Which still passes. So if the *parent* directory doesn't exist `destroy` will return an error. But if it's only the child that doesn't exist, `destroy` is silent.

@ralphtheninja does leveldown have the same behavior?

**Comment by ralphtheninja** [comment]
> OK doing fs.rmdir works!

👍 



> Which still passes. So if the parent directory doesn't exist destroy will return an error. But if it's only the child that doesn't exist, destroy is silent.

I don't know. You would have to test this.

**Comment by vweevers** [comment]
Yup, leveldown works the same. So I'll add a test to leveldown too.
