### ISSUE TITLE
Huge node_modules rocksdb directory - 1.41GB (Windows)

### ISSUE THREAD

**Issue by metabench** [Level/rocksdb#42]
I understand that this is a relatively big, complex piece of software, but was very surprised to see the disk usage quite that high. I am yet to investigate disk usage on Linux, where it would be deployed.

Are there any easy ways to clear out unnecessary files? Would it be worth having an optional cleanup stage as part of the build? My use case does not involve modifying the rocksdb source and recompiling, and I suppose speeding up recompilation is a reason why various files produced during compilation are left behind.

**Comment by vweevers** [comment]
What node version are you on? We have prebuilt binaries, which are only ~4 MB, both on Windows and Linux. That said, perhaps we can optimize the build process (also to speed up AppVeyor builds). 

@mcollina IIRC you were looking into this. Did anything come of it?

**Comment by metabench** [comment]
I'm using node 9.4.0.

I may want to deploy this to a number of remote servers, using `npm
install`, and would like it be be as convenient as possible to get it
running quickly, without excessive disk usage. However, these are Linux and
I don't yet know if there is build clutter (as I see it) left behind to
nearly the same extent.

**Comment by vweevers** [comment]
> I'm using node 9.4.0.

Since 2.0.0 rocksdb has prebuilts for node 9, downloaded upon `npm install`.

**Comment by metabench** [comment]
That does a lot to explain it. I downloaded rocksdb as a dependency for level-rocksdb, and though their github page https://github.com/Level/level-rocksdb mentions 2.0.0 it's clearly not what was installed on my machine.

The LevelDown interface actually looks quite similar to LevelUp, I could maybe change to that.

Being very new to RocksDB. I don't know I've recognised a deficiency in the node/level/rocksdb ecosystem, or have just gone about it the wrong way so far.

Though it's a slightly unrelated question, do you anticipate there would be many complications in changing from a LevelDB LevelUP interface to RocksDB LevelDown? To those who have worked in node, rocks and LevelDown, is there much of an advantage to using a LevelUp interface to access RocksDB?

**Comment by vweevers** [comment]
> That does a lot to explain it. I downloaded rocksdb as a dependency for level-rocksdb, and though their github page https://github.com/Level/level-rocksdb mentions 2.0.0 it's clearly not what was installed on my machine.

Ah, we need to release a new `level-rocksdb`. See https://github.com/Level/level-rocksdb/issues/22.

> The LevelDown interface actually looks quite similar to LevelUp, I could maybe change to that. [.. ] To those who have worked in node, rocks and LevelDown, is there much of an advantage to using a LevelUp interface to access RocksDB?

It is highly recommended to use the levelup interface. Among other things, it manages open state and defers operations when needed. From the [`leveldown`](https://github.com/Level/leveldown) readme (this also applies to `rocksdb`):

> It is strongly recommended that you use levelup in preference to leveldown unless you have measurable performance reasons to do so. levelup is optimised for usability and safety. Although we are working to improve the safety of the leveldown interface it is still easy to crash your Node process if you don't do things in just the right way.

Besides `levelup`, `level-rocksdb` also bundles [`encoding-down`](https://github.com/level/encoding-down).

**Comment by mcollina** [comment]
Thanks @vweevers!

**Comment by metabench** [comment]
@vweevers Reading that text informed my decision to use LevelUp in the first place, but considered using LevelDown for performance reasons, as well as recently because I want to use RocksDB. I consider myself warned about this.

If I want to get started with LevelUP and RocksDB very soon, is there a small amount of code I could use that avoids `level-rocksdb`, and applies the LevelUP interface over the newer `rocksdb`? If so, would you share that code here please?

**Comment by vweevers** [comment]
This will give you the same functionality as `level-rocksdb`:

```js
const levelup = require('levelup')
const rocksdb = require('rocksdb')
const encode = require('encoding-down')

const db = levelup(encode(rocksdb('./db')))
```

**Comment by vweevers** [comment]
@metabench `level-rocksdb` 2.0.0 (with `rocksdb` 2.0.0) has been released.
