### ISSUE TITLE
prebuild-install@4 does not work on mac os v10.13.5

### ISSUE THREAD

**Issue by heri16** [Level/rocksdb#65]
See: https://github.com/prebuild/prebuild-install/issues/83

**Comment by heri16** [comment]
## This works:
```
npm rebuild leveldown --platform=darwin --loglevel verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/heri/.nvm/versions/node/v8.10.0/bin/node',
npm verb cli   '/Users/heri/.nvm/versions/node/v8.10.0/bin/npm',
npm verb cli   'rebuild',
npm verb cli   'leveldown',
npm verb cli   '--platform=darwin',
npm verb cli   '--loglevel',
npm verb cli   'verbose' ]
npm info using npm@6.1.0
npm info using node@v8.10.0
npm info readInstalled object
npm verb rebuild path, id [ '/Users/heri/work/middleware/packages/graphql/node_modules/leveldown',
npm verb rebuild   'leveldown@4.0.1' ]
npm info build /Users/heri/work/middleware/packages/graphql/node_modules/leveldown
npm info lifecycle leveldown@4.0.1~preinstall: leveldown@4.0.1
npm info linkStuff leveldown@4.0.1
npm info lifecycle leveldown@4.0.1~install: leveldown@4.0.1

> leveldown@4.0.1 install /Users/heri/work/middleware/packages/graphql/node_modules/leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 4.0.0
prebuild-install info looking for cached prebuild @ /Users/heri/.npm/_prebuilds/067087-leveldown-v4.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /Users/heri/.npm/_prebuilds/067087-leveldown-v4.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/heri/work/middleware/packages/graphql/node_modules/leveldown/build/Release/leveldown.node
prebuild-install info unpack required /Users/heri/work/middleware/packages/graphql/node_modules/leveldown/build/Release/leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!
```
## This works:
```npm rebuild rocksdb --platform=linux --loglevel verbose```

## This does not:
```
npm rebuild rocksdb --platform=darwin --loglevel verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/heri/.nvm/versions/node/v8.10.0/bin/node',
npm verb cli   '/Users/heri/.nvm/versions/node/v8.10.0/bin/npm',
npm verb cli   'rebuild',
npm verb cli   'rocksdb',
npm verb cli   '--platform=darwin',
npm verb cli   '--loglevel',
npm verb cli   'verbose' ]
npm info using npm@6.1.0
npm info using node@v8.10.0
npm info readInstalled object
npm verb rebuild path, id [ '/Users/heri/work/middleware/packages/graphql/node_modules/rocksdb',
npm verb rebuild   'rocksdb@3.0.1' ]
npm info build /Users/heri/work/middleware/packages/graphql/node_modules/rocksdb
npm info lifecycle rocksdb@3.0.1~preinstall: rocksdb@3.0.1
npm info linkStuff rocksdb@3.0.1
npm info lifecycle rocksdb@3.0.1~install: rocksdb@3.0.1

> rocksdb@3.0.1 install /Users/heri/work/middleware/packages/graphql/node_modules/rocksdb
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 4.0.0
prebuild-install info looking for cached prebuild @ /Users/heri/.npm/_prebuilds/6f44f7-rocksdb-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ /Users/heri/.npm/_prebuilds/6f44f7-rocksdb-v3.0.1-node-v57-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/heri/work/middleware/packages/graphql/node_modules/rocksdb/build/Release/leveldown.node
sh: line 1:  8456 Illegal instruction: 4  prebuild-install
gyp info it worked if it ends with ok
gyp verb cli [ '/Users/heri/.nvm/versions/node/v8.10.0/bin/node',
gyp verb cli   '/Users/heri/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
```

Rocksdb is a fork of Leveldown.

If leveldown works, it just means that precompiled rocksdb does not work on darwin? Or uses certain x86 extensions that is not supported on my hardware? I just verified that it works on docker-for-mac on the same hardware after doing `npm rebuild --platform=linux`

Is this a downstream issue then?

**Comment by ralphtheninja** [comment]
What happens after you get the `Illegal instruction` error? I can tell from the log that it falls back to compilation. Does _that_ succeed?

**Comment by heri16** [comment]
Yes, fallback compilation succeeds, but that results in static libraries that are 400MB in size in my build/Release folder.

**Comment by vweevers** [comment]
I asked a friend with latest 10.13 to replicate `Illegal instruction`, they could not. On 10.13.5 / darwin 17.6.0, node 8.11.2.

**Comment by vweevers** [comment]
Hunting for someone with 10.13.3 😄

**Comment by heri16** [comment]
@vweevers could your friend try installing node 8.10 from nvm (node version manager)?

**Comment by vweevers** [comment]
I highly doubt that's the issue.

**Comment by heri16** [comment]
Issue: Loading of precompiled rocksdb failed.

Let me just enumerate the possible causes:
- Nodejs binaries/variant (~/.nvm/versions/node/v8.10.0/bin/node)
- Operating System version (changes in binary compatibility)
- Definitely not build tools.
- Definitely not npm version.
- Hardware?

Is there anything I missed?

**Comment by ralphtheninja** [comment]
We're building the binaries on Travis and at first I thought that we might be building the binaries on a newer version of mac osx which for some reason is not binary compatible with 10.13.3, but this is probably not the issue either since we're building on 10.12, unless building on an _earlier_ version can be problematic

From https://travis-ci.org/Level/rocksdb/jobs/382215238

![screenshot from 2018-06-14 11-51-38](https://user-images.githubusercontent.com/308049/41405147-557c7e8c-6fc9-11e8-9df1-dfbfc9d04f3f.png)

**Comment by heri16** [comment]
GCC Flags needs tuning:
https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

CPU hardware is old:
https://github.com/muammar/mkchromecast/issues/4

**Comment by ralphtheninja** [comment]
We use `-mmacosx-version-min` here

https://github.com/Level/rocksdb/blob/de48d2bd40896da35181a8a1ccc700497ffd1a5f/binding.gyp#L38

Looks alright to me.

**Comment by ralphtheninja** [comment]
@heri16 What happens if you switch node version to e.g. 9 or 10?

**Comment by vweevers** [comment]
Related:

- https://github.com/facebook/rocksdb/issues/692#issuecomment-131883982
- https://github.com/facebook/rocksdb/issues/690
- https://github.com/facebook/rocksdb/issues/1278
- https://github.com/facebook/rocksdb/issues/2585#issuecomment-317890558

> Looks like the rocksdb was compiled with PORTABLE flag set turned off (which is the default). When PORTABLE flag is turned off, we compile RocksDB to optimize for native architecture. This makes the binary work only on that specific architecture.

**Comment by vweevers** [comment]
And https://github.com/facebook/rocksdb/blob/master/INSTALL.md#compilation:

> By default the binary we produce is optimized for the platform you're compiling on (-march=native or the equivalent). SSE4.2 will thus be enabled automatically if your CPU supports it. To print a warning if your CPU does not support SSE4.2, build with USE_SSE=1 make static_lib or, if using CMake, cmake -DFORCE_SSE42=ON. If you want to build a portable binary, add PORTABLE=1 before your make commands, like this: PORTABLE=1 make static_lib.

**Comment by ralphtheninja** [comment]
https://github.com/Level/rocksdb/commit/d306227fd56089ee8e26def5122afcebdb7d6116

I'm building a prepatch version that we can try out.

**Comment by vweevers** [comment]
👏

**Comment by ralphtheninja** [comment]
Also TIL about `SIGILL` :)

**Comment by vweevers** [comment]
Using `PORTABLE=1` does have a performance cost, perhaps we should document that?

**Comment by heri16** [comment]
How big is the performance difference? Does this change affect Linux, Windows also?

Can the PORTABLE flag be read by prebuilt-install during npm rebuild? Would we consider having  sse4 variants of rocksdb and those without?

**Comment by ralphtheninja** [comment]
@heri16 Can we at least try this out first. We don't even know if it works yet. Thanks.

**Comment by ralphtheninja** [comment]
At time of writing we're still missing binaries for node 10, but since @heri16 is using node 8 I'm publishing a bit in advance.

You can try this release by doing `npm i rocksdb@3.0.2-0`

**Comment by ralphtheninja** [comment]
If this works well and `PORTABLE` doesn't imply huge difference in performance I think we should enable it by default.

**Comment by ralphtheninja** [comment]
@vweevers Wanna help out checking the difference in performance? There's some scripts in the `bench/` folder.

**Comment by vweevers** [comment]
Sure

**Comment by vweevers** [comment]
On Windows, `bench/write-random.js` shows decreased perf and curiously, an increased database size:

![image](https://user-images.githubusercontent.com/3055345/41487365-c2ef317e-70e8-11e8-95ae-ea8d33b40d29.png)

**Comment by ralphtheninja** [comment]
@heri16 So does this release work on your machine?

**Comment by heri16** [comment]
Thanks so much everyone! I currently am out for vacation and don't have access to my machine. Will report back tomorrow, very likely with good news.

**Comment by ralphtheninja** [comment]
@vweevers I'm wondering if the db size could be related to compaction as well. We could also run benchmarks multiple times.

**Comment by vweevers** [comment]
> I'm wondering if the db size could be related to compaction as well.

Lemme try `db.compactRange()`.

**Comment by vweevers** [comment]
Yes, you were right. Before and after manual compaction:

```
Database size: 549M
Database size: 347M
```

**Comment by vweevers** [comment]
I think compaction (or flushing to disk?) affects the benchmark too. Every so often there are ~10 writes that take much longer:

```
11252,114248
11612,359966939
11612,360000790
11612,360026884
11612,360064261
11612,360031115
11612,360036756
11612,360030057
11612,360052977
11612,360035347
11612,360058972
11612,179482
```

**Comment by ralphtheninja** [comment]
@heri16 Any news?

@mcollina Any thoughts on enabling `PORTABLE=1`?

**Comment by vweevers** [comment]
@ralphtheninja did you check the perf on linux, or are you waiting for @heri16 to test?

**Comment by ralphtheninja** [comment]
@vweevers Checking perf now. Would be nice with a cli tool for this to chew on the resulting `.csv` file. I'm opening it in open office and it only accepts a limited size of the data set.

**Comment by ralphtheninja** [comment]
![screenshot from 2018-06-19 16-46-42](https://user-images.githubusercontent.com/308049/41604813-6220e3b0-73e0-11e8-84ea-e3492b6eddfc.png)

Quite interesting. I get even better performance with `PORTABLE=1`.

**Comment by vweevers** [comment]
>  What's the limit of open office?

Nevermind, just saw your edit

**Comment by heri16** [comment]
Seems like i am still getting the same error

```bash
> npm i rocksdb@3.0.2-0

> rocksdb@3.0.2-0 install /Users/heri/work/eqh-middleware/packages/eqh-graphql/node_modules/rocksdb
> prebuild-install || node-gyp rebuild

sh: line 1: 54948 Illegal instruction: 4  prebuild-install
```

**Comment by mathiask88** [comment]
@heri16 To verify that the SIGILL does come from an unsupported CPU feature you can run `gdb --args node -e "require('./')"` in rocksdb directory and when you hit the error just type `layout asm` and you see the instruction that raised the error. If you don't have gdb installed on your mac, you can use LLDB instead, but I don't know the respective commands. But there should be a way to display the assembly as well.
