### ISSUE TITLE
createReadStream with Binary data

### ISSUE THREAD

**Issue by cisaacson** [Level/rocksdb#68]
I have a database with key/value encoding: 'binary'. Both put/get work fine using a node Buffer as the key/value. Now I want to use createReadStream with a range (gte,le) and I am not getting results back. I tried a test with 'hex' encoding on the same values (in hex form derived from the Buffer objects) and it worked fine, just not with Buffers themselves. The BytewiseComparator is the default in the configuration.

My question is: When using the BytewiseComparator with binary keys (node Buffer objects) and createReadStream, does it still do a byte-by-byte comparison? My actual key is longer than the 'gte/le' range keys, but if it works byte-by-byte then the 'gte/le' keys definitely include the range of the data in the database. If it is doing a number comparison on the entire range key and data key then it would not be in the range, since there are fewer bytes in the range keys than the data. 

Here is a pseudo example in hex representation of what the data looks like (spacing for readability):

gte key:
`05000000 15 01000000 1a01 00 2201 00`
data key:
`05000000 15 01000000 1A08 5912F421E64A4000`
lt: key:
`05000000 15 02000000 1a01 00 2201 00`

You can see that `01000000 1a01` < `01000000 1A08` < `02000000 1a01` based on a byte-by-byte comparison.

I can convert to using 'hex' encoding for the keys, but it would be great if I can get it to work with pure binary.

Any help appreciated.

**Comment by vweevers** [comment]
Can you provide some code, from your db setup to `createReadStream`?

**Comment by cisaacson** [comment]
I created a standalone test and it is working as expected, I must have something else wrong in my code. I'll close the case, thanks for getting back to me so quickly.

**Comment by cisaacson** [comment]
Got it thanks, I will fix that too.
