### ISSUE TITLE
Open rocksdb in ReadOnly Mode

### ISSUE THREAD

**Issue by cisaacson** [Level/rocksdb#72]
Is there an option that can be passed to level/rocksdb to open rocksdb in ReadOnly Mode? I see how to do it from native code, but not from the `level(path, options)`. I would like to have one process in read/write mode, and another process in ReadOnly mode (even if that means it is only a snapshot of the database at the time of open, that is OK).

**Comment by eugeneware** [comment]
@cisaacson I've created a PR for this in #98 and also published a personal fork of the leveldown module at [@eugeneware/rocksdb](https://www.npmjs.com/@eugeneware/rocksdb)
